### PR TITLE
Infra 001 repository naming conventions odr

### PR DESCRIPTION
**Pull request by Polichinel**
First ODR  (Organizational Decision Record ) for our new organization and the /docs repo. Please read the ODRs/README.md and check the ODRs/odr_template.md before reviewing.

:vulcan_salute:

### CODE REVIEW

**Review by smellycloud — APPROVED** [review]
Looks good to me

**Review by lujzi05 — APPROVED** [review]
Good to have three-word limit!

**Comment by xiaolong0728** [comment]
Looks good to me. When I wrote ADRs, I was always thinking about how to organize (order) them in a proper way because the number of ADRs addressing similar topics can be very discrete. But now this problem is solved.

**Review by jimdale — APPROVED** [review]
Looks very sensible to me :)

**Pull request merged**
